export const SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN;
export const SENTRY_ENVIRONMENT = process.env.NEXT_PUBLIC_SENTRY_ENVIRONMENT;
export const INFURA_ID = process.env.NEXT_PUBLIC_INFURA_ID;
export const REACT_APP_CLIENT_ID = process.env.NEXT_PUBLIC_REACT_APP_CLIENT_ID;
export const GITPOAP_API_URL = process.env.NEXT_PUBLIC_GITPOAP_API_URL;
export const DISCORD_CLIENT_ID = process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID;
export const AMPLITUDE_TOKEN = process.env.NEXT_PUBLIC_AMPLITUDE_TOKEN;
